name: Build on Main Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (if applicable)
        if: matrix.os == 'ubuntu-latest' && steps.node-version.outputs.node-version
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: npm install

      - name: Build project
        if: matrix.os == 'ubuntu-latest'
        run: npm run build

      - name: Set up MSYS2 (if applicable)
        if: matrix.os == 'windows-latest'
        uses: actions/setup-msys2@v1

      - name: Install dependencies on Windows
        if: matrix.os == 'windows-latest'
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm make mingw-w64-x86_64-gcc

      - name: Build project on Windows
        if: matrix.os == 'windows-latest'
        run: npm run build:windows

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-artifacts
          path: |
            ${{ matrix.os == 'windows-latest' ? 'path/to/windows/artifacts' : 'path/to/linux/artifacts' }}
